project:
  type: website
  render: 
    - Notes_MAS_Chapter_2.qmd

website:
  title: "Measurement_Systems"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



