---
title: "Measurement Systems: Science, Philosophy, Engineering"
author: "Brad Venner"
date: "05/23/2023"
output: html_document
---

# Design

A 16 week semester with 3 lectures per week gives 48 total lectures. At some point, each lecture should introduce a key concept or problem in measurement. An introductory course, particularly one focused on developing a trans-disciplinary approach to measurement, can only scratch the surface of the subject. On the other hand, the course should emphasize the basics so that students leave with the confidence to design/improve measurement systems. I think this means that practical subject such as measurement systems analysis and validation should be included. Obviously the VIM provides a list of concepts.

Potential textbook: Measurement Across the Sciences. This book focuses on a conceptual understanding of measurement (aka philosophy of measurement) as they might be realized in physical and social measurements. Mari's two co-authors are educational measurement specialists. The last chapter on semiotics of measurement could serve as an outline for the course. The question is whether this is a good design or not. Because semiotics can seem so vague, does it make sense to only bring it up at the end. On the other hand, much of the discussion in the book around properties could be interpreted using Peirce's understanding of a proposition. This made me think about Stjernfelt's analysis of natural propositions.

Potential textbook: Handbook of Measuring System Design. Focuses on physical measurement systems. Does include sections on systems thinking and life cycles. Includes several articles from Finkelstein on philosophy of measurement that might be interesting.

Potential textbook: Measurement Theory and Practice. By D. J. Hand. Develops a "pragmatic" theory of measurement that is "somewhat" related to the "semiotic" theory.

Potential textbook: General Systemology. By David Rousseau et. al. Develops a "reasonable" typology for a general philosophy of systems. Discusses transdisciplinarity facilitated by general systems. Proposes "general systems methodologies", 

## Course organization

Going over this on March 25, 2025, it seems like the "phased" approach to introducing concepts will fail. I'm not sure that asking students to wade through lots of theory development without introducing the "simplest" measurement systems first would be the best approach. 

I still like the idea of introducing the notion of grading early in the course and using this as an ongoing example. But would it be possible to introduce something like the measurement of length as an initial example and move towards more sophisticated measuring systems? 

# Introduction
1. Who am I? Who are you?

2. Transdisciplinary Frameworks

    a. Systems
    b. Semiotics

3. Course structure
    a. Readings. Provide electronic versions of all documents on a document management system.
    b. Discussion. Each section has a practical running example. Discussions are intended to be cumulative.
    c. Programming. A domain-specific language for measurement systems. Probably in Julia for now, but Agda is a possibility. Include statistical analysis in course design, as well as probabilistic systems.
    d. Exams. These should be both subject and object. Particularly with Luca's ongoing example.
    e. Final project: Design or improve a measurement system, preferably in your major.

# Overview: Measurement, systems, semiotics

One classic piece of rhetoric (advice) for structuring a talk is to tell your audience what you're going to tell them, tell them, then tell them what you told them. A risk of this structure is that the introduction, the high-level overview, runs the risk of being too abstract and therefore confusing.

As we previously discussed, measurement, systems and semiotics have all been proposed as transdisciplinary frameworks. The "thesis" of this course is that these are related frameworks and that each has something to contribute to the study of measurement systems.

According to Cropley [@cropley:1998:towards_2], Finkelstein was the first to link semiotics and the measurement process.

## Reading: Chapter 8 of Luca

Chapter 8 of Luca was written as the concluding chapter of their book and therefore makes references to previous chapters. 

Of our three transdisciplinary frameworks, semiotics was developed at the highest level of abstraction and was intended to be the most inclusive. Measurement is the least inclusive and is the most opinionated. So all measurements are signs, but not all signs are measurements.

Insert "natural transformation graph" that shows the relationship between the concepts.

Insert Lawvere's nested Sierpinski diagram. 

## Lecture: Measurement by systems

Luca calls this "syntax"

## Lecture: Measurement of systems

Luca calls this "semantics". Relationship between measuring system and "system under measurement". Peirce's "actuality".

## Lecture: Measurement for systems

Luca calls this "pragmatics". Peirce called it "normative" or "would-be". Measurement as a purposeful activity.

## Discussion: Are grades measurements? 

# Measurement

Metrology is defined as the science of measurement. From the viewpoint of measurement as a trans-disciplinary framework (aka a doctrine), it has scientific, mathematical and philosphical dimensions.


I'm not sure this should be a separate section. Luca contains parallel physical/psychical examples. I probably should stick to the textbook organization. Chapter 2 of Mari outlines basic concepts, not all of VIM

## (Subfields)[https://en.wikipedia.org/wiki/Metrology]

1. natural metrology - measurands, units of measurement

2. technical metrology - measuring systems, realization of units in practice

3. social metrology - utilization of measurement systems in society. AKA legal metrology.

## Concepts and vocabulary in metrology

## Metric system

## National measurement systems

# Systems

# Semiotics

> Working on the assumption that one of the shared goals of this list discussion is to consider the various ways that mathematical systems of logic might be used to foster more rigorous forms of inquiry in philosophical logic, then we might gain something by looking at Peirce's clarifications of these conceptions in measurement theory--which is largely a matter of applied mathematics. See CP 7.280-312. 
