---
title: "Notes on Measurement Across the Sciences, Chapter 3"
author: "Brad Venner"
date: "5/16/2025"
output: html_document
---
## 3.2 The Quality of Measurement and Its Results

This section covers measurement quality in general and has specific discussions about measurement error and measurement uncertainty. These topics are discussed in more detail in Section 7 of the text, and touched on in Section 4 and 8. They introduce the complementary aspects of object-relatedness and subject-independence in Section 7.

This style of the text of systematically unfolding concepts in measurement could be improved by examining examples of increasingly complex measurement systems. This is clearly a challenge in an inter-disciplinary text, but their use of the same two examples throughout the text doesn't fit the increasing refinement style of the book.

On the other hand, I think it could be really interesting and rewarding to have a class that included both natural and human science students, and this fits the overall theme of the book.

> ... two measurement processes implementing the same procedure on the same objects may produce different results.

Possible reasons:

1. the property of the object has changed,

2. the "state" of the measuring instrument has changed,

3. the "state" of the environment has changed.

An "affecting property" is any property whose changes produce a change in the measured property. I think that in quantum measurement this is modeled by a change in "state" that leads to a change in an "observable". Note that the other two reasons are formulated as a change in state, while the change in the object is attributed to a property. Mari gives an example of the environment changing the measured property, but the interaction with measuring system can also cause a change, with quantum measurement and destructive measurement being two examples. (maybe a "disturbing measuring system" is the common root. It doesn't look like I have my quantum measurement references on ny work computer, but I will need to add some quantum measurement components to this course as this aspect is not covered by Mari.) 

An "influence property" is, by symmetry, any property of the measuring system that alters the behavior (i.e. the transduced property) of the measuring system. 

Although Mari doesn't mention it here, the object may also have "influence properties" (e.g. carryover) that change the state of the measuring system. This interactive symmetry (i.e. that an interaction can change both the measured and measuring system) calls to mind "symbolic interactionism" in sociology (at least the vague understanding I have of Mead's work.) I'd like to understand the difference between late Dewey's "transactionalism", Mead's "symbolic interactionalism", Castoriadis' semiotics, and Peirce's semiotics.

Mari identifies two basic strategies to deal with "influence properties," assuming that they can be identified.

An *empirical* strategy tries to reduce the sensitivity of influence properties of the measuring system (Mari uses "instrument").

An *informational* strategy tries to model, evaluate, and formally express influence properties and then provide an evaluation of the "quality" of the measurement result.

My sense is expressing this as a duality is incorrect, as estimates of measurement quality depend upon empirical "experiments." I would argue that the "top-down" and "bottom-up" distinction is similar to this empirical/informational distinction, but expressed in terms of the "measurement model", with top-down models being more statistical and bottom-up models being more physical, with some future "digital twin" model capturing both aspects.

> Measurement is essentially a production process, the product being numbers. (Speitel, 1992)

> as such, the quality of the products and the quality of the process are in principle distinct (though plausibly related), and as such they each deserve some consideration. [p. 52]

ISO 17025 does not really include the distinction between "measurement process" and "measurement procedure". However, VIM4 defines measurement as 

> a process of experimentally obtaining one or more values that can reasonably be attributed to a quantity together with any other relevant information [VIM4, 2.1]

Note 5 to this definition requires for reasonable attribution "the intended use of a measurement result" (i.e. purpose), a "measurement procedure" (which includes a measurement model by reference) and a "measuring system".

Aside: Mari distinguishes between terms enclosed in double quotes and concepts identified in angle brackets, which he says is standard in ISO documents. This is problematic in Markdown, which reserves angle brackets for HTML entries. One possibility would be to build an explicit glossary 