---
title: "Category theory applied to semiotics, aka categorical semiotics"
author: "Brad Venner"
date: "8/18/2025"
output: html_document
---

One of the inherent challenges of applied category theory for any scientific domain is the inherent flexibility of many of the basic notions of category theory. Often these have arisen from generalizations from areas of abstract mathematics. The problem of applications is how these abstract mathematical concepts relate to "philosophical" concepts and in turn how they relate to empirical "scientific" concepts. Trinitarianism in its various disguises (most explicitly semiotics) relates the "informational" domain to the "empirical" domain by granting a certain basic reality to "experience" that is not "conceptual". 

Peirce attempted to ground mathematical practice in a perception-action cycle where possible operations on diagrams are perceived and manipulations of diagrams as forms of experiments are performed. But "perception" and "manipulation" are also represented as concepts, and there is a need to "pull" in the empirical domain into the formal system. In one of his more famous quotes, Peirce said

> The elements of every concept enter into logical thought at the gate of perception and make their exit at the gate of purposive action; and whatever cannot show its passports at both these two gates is to be arrested as unauthorized by reason. (EPII, 241, 1903)

One of the purposes of measurement science is to provide a "grounding" to this potential infinite regress. Can the "formal" models of "measurement science" be grounded in "non-conceptual" empirical perceptions and actions? Other disciplines that take this problem seriously are cognitive science, systems science and computer science. One of the advantages of semiotics over the last two approaches is that the concept of "cognition" is not necessary for the definition of "sign" and this allows the emergence of "signs" to predate the emergence of \(human\) cognition. Peirce advocated for a notion of the sign that was prior to the emergence of life, which Deely called *physiosemiosis*. This concept could potentially be important for the concept of "measurement." has played an important role in quantum systems. Measurement science must wrestle with the quantum measurement problem and measurement as a "semiotic" process should be consistent with it. Although Mari does not consider the quantum measurement problem in his book, it is important that any proposed formalization does not "beg the question" of quantum measurement.    