---
title: "Observables and measurands"
author: "Brad Venner"
date: "4/8/2026"
output: html_document
---

How are the concepts of an observable in physics and the measurand in metrology related? Wikipedia's entry on (observable)[https://en.wikipedia.org/wiki/Observable] states that:

> In physics, an observable is a physical property or physical quantity that can be measured. In classical mechanics, an observable is a real-valued "function" on the set of all possible system states, e.g., position and momentum.

This definition does several things. It identifies an observable with an "attribute" (property or quantity) of a physical system. It also implicitly defines an object with a "region" of a state space and the link between an object and a property as functional. The state space is inherently abstract and therefore unmeasurable.

There is an implicit species-genus relationship between *observable* and *measurand*. Perhaps biological or psychological object-properties are not observables. In Chapter 5, Mari argues that they maintain the "object/property" relationship. An "empirical property" is defined as "*a mode of empirical interaction of the object with its environment.*"  This definition says almost nothing about the object (or it's mereology), does not distinguish between essential and accidental properties, or distinguish between primary properties (object-specific, e.g. mass) and secondary properties (observer-related, e.g. perceived color). Mari explicitly claims that this definition can admit "the existence of non-physical properties." In other words, there is no commitment to objects residing in some sort of space. It's also not clear that the notion of a physical property that can be measured is necessarily the same thing as a real-valued function on a state space. It seems like the assertion that every real-valued function on a state space is an observable is in general an assertion about an infinite dimensional function space that has it's own topology and mereology.

Could Willem's behavioral approach to systems theory provide a more physically-grounded theory of observables? Willem's provides examples from classical mechanics but (perhaps?) does not distinguish between states and observables, as his notion of "behavior" seems to be defined on the state space and not the observable space. Interaction between systems should be variable sharing between observables. This is explicit in port-Hamiltonian systems, where energy is clearly an observable.

Jaz Meyer's work on categorical systems theory does include a "strong" notion of system and observable. I have concerns about the commitment to the notion of a system as a global element in an interface type in double operadic systems theory but I need to have a better understanding of the details before I can say more about that. 

Another way of proceeding would be to focus on port-Hamiltonian systems, which "stress" the classical notion of observable. Jonas Kirchhoff develops *A behavioural approach to port-Hamiltonian systems*. This paper does not reference the categorical systems theory of Meyers or ??? but does reference Schultz et. al. *Dynamical Systems and Sheaves*. [@schultz:2020:dynamical]. They state that the "continuous machines" defined in Schultz is a better They state that Willem's definition of a behavior is a trajectory on a "signal space", so this theory works with the observable space.

I'm afraid I don't really understand the distinction between state space and observable. In particular, the notion of "position" as an observable is not clear to me. How is position not a position in a state space? One answer would be the question "position of what?". A variety of objects can have a position, so position is a "universal". Mohrmann's approach to structural mereology might help here, as the position of an object can be a part of a trajectory. Position is an "essential property" in the sense that it's hard to imagine an object without a position. Another way to think about this is that there is a continuum and "position" is a region of that continuum. This makes it an observable.

Since an observable is a real-valued function on a phase space, a phase space is a "set" of all possible physical states, and a position is a component of a physical state, then a position is an element of a state space. So does this make an observable a map from 1 -> P, where P is the position type, and type is a synonym for all possible positions? In other words, is the "functional relationship" a global element, i.e. a map from 1 to the space? Synthetic differential geometry extends this idea to "infinitesimals" that are maps from the "infinitesimal interval" to the space. Paths are maps from an "interval type" to the space. Lawvere approaches questions of continuum physics from a very abstract viewpoint and I can see the need to read his work very deeply if I want to understand these more ontological questions.   