---
title: "Symbol Grounding Problem"
author: "Brad Venner"
date: "8/11/2025"
output: html_document
---
There is no a priori basis for the belief that formal semiotics must be expressed in category theory. Abbreviating "category theory in formal semiotics" as "categorical semiotics" implies that formal semiotics is mathematical semiotics, and that category theory is the distinguished form of mathematics in which to do this analysis.

The same process has occured in logic. Logic was detached from analysis of broad problems in philosophy to become mathematical logic. The two terms of "mathematics" and "logic" were understood to be synonymous by early logicists such as Russell and Frege. Mathematical logic was understood to them as first-order logic. As mathematical logic became more powerful and developed its own tools and approaches, there was a move in philosophy to reconnect to mathematical logic that became "logical empiricism" and then "analytical philosophy" (although this history is complex). Rather than expanding the power of formal systems to express and solve problems that were expressed in natural language, there was an attempt to narrow the domain of philosophy to work on problems that could be expressed in mathematical logic.

Category theory was then applied to understand mathematical logic and become "categorical logic." William Lawvere, who did much of this early work, was sympathetic to the Hegelian tradition in logic and also very interested in the application of category theory to physical systems. Several of his papers mention "objective logic" - can this be thought of as linking the formal systems of category theory. 

To a certain extent, artificial intelligence has worked against logicism, although it has certainly been influenced by it. Symbolic artificial intelligence, or what the Stanford Encyclopedia calls (logic-based artificial intelligence)[https://plato.stanford.edu/entries/logic-ai/] may have been influenced by early logicism, there has been a vast expansion of the formal systems used in symbolic AI.

Luc Steels claimed in a 2008 chapter in the book "Symbols and embodiment: debates on meaning and cognition" [@vega:2008:symbols] that *The symbol grounding problem has been solved, so what's next?* [@steels:2008:symbol]. Steels references Lawrence Shapiro's chapter in the book called *Symbolism, embodied cognition and the broader debate* [@shapiro:2008:symbolism]. Shapiro wrote a book entitled *Embodied Cognition* in 2011 [@shapiro:2011:embodied], which a reviewer said was "one of the first detailed book length attempts to introduced and develop the central themes of embodied cognition, an important trend in cognitive science" [@martiny:2011:book]. Embodied cognition is now one of the 4 E's of 4E cognitive science.

Steels develops the notion of a "semiotic network" as how an agent relates objects, concepts and words and a "semiotic landscape" that represents the semiotic networks of multiple agents that may interact in various ways. This type of representation tends to neglect the role of the environment. There is a similar idea around *vector bundles* that relate manifolds, points and vector spaces at each tangent space. It is the manifold that forces relations between vector spaces at various points that is analogous to the common "environment" among agents. Note that "vector bundles" are a special case of "fiber bundles". Fibrations are a leading model of categorical logic so that the notion of a logic "fibered over" a type theory may have more than a passing resemblance to a "semiotic landscape" over the "semiotic networks" of individuals. In the language of fiber bundles, the "semiotic landscape" is the "total (fiber) space", a "semiotic network" is a fiber, and the base space is the "language community" shared by the agents. The main difference is that it does not appear that the "fibers" interact whereas "semiotic networks" do, so this is more a suggestive model than a real categorization. In Steels' analysis, the common environment of a language community allows for sharing of "perceptual judgments" such as "red" (an individual property within the general property "color") to allow for "joint action and communication".

Steel argues that "supervised learning" of robotic systems allows for robots to use to learn symbols in real-world interactions. This paper obviously pre-dates the rise of transformer-based architectures and was written during the rise of "deep learning". Although it's certainly possible that "deep learning" develops features such as "concepts", it is still an open problem in how to extract these into more explicit "symbols".

The role of models in measurement is analogous to the symbol grounding problem in logic. Measurement produces symbols that are used in models, but measurement depends upon models expressed in symbols. Any formalization, whether in natural or technical language, has to bring the external world within the formal system via symbols. Mari calls his solution "model-based realism".